"""Create a RAM-only XIAO finder from the pinned, local upstream commit."""
from pathlib import Path
import ast
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
REV = "68fb8cd8a9bca943a7aa0bd3acf349cca215328b"


def source(path):
    return subprocess.check_output(
        ["git", "show", REV + ":src/" + path], cwd=ROOT, text=True)


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise RuntimeError("Unexpected upstream source near: " + old[:70])
    return text.replace(old, new, 1)


def build():
    driver = source("bc5602/__init__.py")
    driver = replace_once(driver, "from machine import Pin, SPI",
                          "from machine import Pin, SoftSPI")
    start = driver.index("        platform = sys.platform")
    end = driver.index("        # Configure GIO2", start)
    driver = driver[:start] + '''        self._cs = Pin(18, Pin.OUT, value=1)
        self._sck = Pin(20, Pin.OUT)
        self._mosi = Pin(19, Pin.OUT)
        self._miso = Pin(17, Pin.IN)
        self._spi = SoftSPI(baudrate=500000, polarity=0, phase=0,
                            sck=self._sck, mosi=self._mosi, miso=self._miso)

''' + driver[end:]
    driver = replace_once(driver,
        "        # Configure GIO2 as SPI data output: 4-wire mode\n"
        "        self.set_register(IO1_REGISTER | CMD_WRITE_REGISTER, 0b01001000)",
        "        # XIAO wiring: route SDO to BM5602 GIO4.\n"
        "        self.set_register(IO1_REGISTER | CMD_WRITE_REGISTER, 0x40)\n"
        "        self.set_register(IO2_REGISTER | CMD_WRITE_REGISTER, 0x10)")
    driver = replace_once(driver,
        "self.read_register(CMD_READ_CHIP_VERSION | CMD_READ_REGISTER, bytes=3)",
        "self.send_command(CMD_READ_CHIP_VERSION, read_bytes=3)")

    finder = source("find_halo2_address.py")
    # Inline upstream's driver so mpremote run needs no installed modules.
    finder = replace_once(finder, "import bc5602\n", "")
    finder = replace_once(finder, "bc5602.bc5602()", "bc5602()")
    finder = re.sub(r"\bbc5602\.", "", finder)
    finder = replace_once(finder,
        "# Configure GIO2 as SPI data output: 4-wire mode\n"
        "_bc5602.set_register(IO1_REGISTER | CMD_WRITE_REGISTER, 0b01001000)",
        "# XIAO wiring: restore GIO4 SDO, as in driver initialization.\n"
        "_bc5602.set_register(IO1_REGISTER | CMD_WRITE_REGISTER, 0x40)\n"
        "_bc5602.set_register(IO2_REGISTER | CMD_WRITE_REGISTER, 0x10)")
    # Observation only: deadline/logging; preserve upstream decode and RF setup.
    finder = replace_once(finder, "while True:\n", '''started = time.ticks_ms()
last_log = started
raw_count = 0
print("LISTEN 60 seconds: upstream finder, channel 5, strict right shift")
while time.ticks_diff(time.ticks_ms(), started) < 60000:
    if time.ticks_diff(time.ticks_ms(), last_log) >= 5000:
        print("Waiting: packets=%d strict_matches=%d" % (raw_count, addresses_count))
        last_log = time.ticks_ms()
''')
    finder = replace_once(finder,
        "        data = shift_right_one_bit(_bc5602.receive_data(rxd_len, shift_one_bit=False))[7:12]",
        "        raw = _bc5602.receive_data(rxd_len, shift_one_bit=False)\n"
        "        raw_count += 1\n"
        "        if raw_count <= 20:\n"
        "            print('RAW:', raw.hex())\n"
        "        if len(raw) < 12:\n"
        "            continue\n"
        "        data = shift_right_one_bit(raw)[7:12]")
    finder = replace_once(finder, "counts = {}\n",
        "print('RESULT packets=%d strict_matches=%d' % (raw_count, addresses_count))\n"
        "if addresses_count < 5:\n"
        "    raise RuntimeError('Upstream finder did not collect five strict matches; no address saved')\n"
        "counts = {}\n")
    finder = replace_once(finder,
        'with open("/halo2_address.py", "w") as f:\n    f.write(most_frequent)',
        "print('UPSTREAM CANDIDATE:', most_frequent)\n"
        "print('Candidate printed only; saved address unchanged')")
    # The try/finally ends RX even when the timed finder raises or is interrupted.
    combined = ('# Generated by tools/build_upstream_baseline.py from ' + REV + '\n'
                + driver + '\nprint("UPSTREAM BASELINE 1: XIAO SoftSPI/GIO4")\n'
                + 'try:\n' + ''.join('    ' + line + '\n' for line in finder.splitlines())
                + 'finally:\n'
                + '    if "_bc5602" in globals():\n'
                + '        _bc5602.send_command(CMD_LIGHT_SLEEP)\n')
    ast.parse(combined)
    output = ROOT / "build/upstream_baseline/finder.py"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(combined)
    print(output)

    # Reuse the upstream setup, but explicitly control CE between trials.
    setup = finder[:finder.index("addresses = []")]
    setup = replace_once(setup, "_bc5602 = bc5602()",
        "_bc5602 = bc5602()\n"
        "print('ENTRY CE=%02X OM=%02X' % (_bc5602.read_register(0xD5)[0], "
        "_bc5602.read_register(0xE0)[0]))\n"
        "_bc5602.set_register(0x55, 0)\n"
        "_bc5602.set_register(0x60, _bc5602.read_register(0xE0)[0] & ~8)")
    setup = replace_once(setup, "_bc5602.send_command(CMD_RX_MODE)", "")
    probe = '''
def snapshot(label):
    print(label, " ".join("%s=%02X" % (name, _bc5602.read_register(reg)[0])
        for name, reg in (("MASK", 0xC3), ("CE", 0xD5), ("OM", 0xE0),
                          ("STA1", 0xE6), ("STATUS", 0xC5), ("CFG1", 0xC0),
                          ("RC1", 0xC1), ("PEN", 0xF7), ("DM1", 0xD1),
                          ("PKT1", 0xC9), ("PKT2", 0xCA), ("PKT3", 0xCB),
                          ("DPL1", 0xEA), ("DPL2", 0xEB), ("RXPW0", 0xEC),
                          ("ENAA", 0xF2), ("IO1", 0xC6), ("IO2", 0xC7),
                          ("IO3", 0xC8))))

for method in ("CE before radio reset", "CE after radio reset"):
    _bc5602.set_register(0x55, 0)
    if method == "CE after radio reset":
        snapshot("PRE-RESET")
        _bc5602.send_command(CMD_SOFTWARE_RESET)
        time.sleep_ms(5)
        # Recreate the transport and apply exactly the same upstream setup.
__RESET_SETUP__
    time.sleep_ms(5)
    if _bc5602.read_register(0xD5)[0] & 1:
        raise RuntimeError("Cannot clear CE; comparison aborted")
    snapshot("BEFORE " + method)
    _bc5602.set_register(0x55, 1)
    time.sleep_ms(10)
    snapshot("AFTER " + method)
    count = 0
    started = time.ticks_ms()
    while time.ticks_diff(time.ticks_ms(), started) < 10000:
        if not (_bc5602.read_register(0xC5)[0] & 1):
            length = _bc5602.read_register(0xCC)[0]
            if not 1 <= length <= 32:
                raise RuntimeError("Invalid RX length: %d" % length)
            raw = _bc5602.receive_data(length)
            count += 1
            if count <= 5:
                print("RAW:", raw.hex())
        time.sleep_ms(2)
    print("RESULT %s packets=%d" % (method, count))
    snapshot("END " + method)

_bc5602.send_command(CMD_LIGHT_SLEEP)
time.sleep_ms(10)
snapshot("AFTER light-sleep command (CE should clear)")
print("DONE: no address saved")
'''
    probe = replace_once(probe, "__RESET_SETUP__",
                         '\n'.join('        ' + line for line in setup.splitlines()))
    check = (driver + '\nprint("RX START CHECK 2: identical setup before/after radio reset")\n'
             + 'try:\n' + ''.join('    ' + line + '\n' for line in (setup + probe).splitlines())
             + 'finally:\n'
             + '    if "_bc5602" in globals():\n'
             + '        _bc5602.set_register(0x55, 0)\n'
             + '        _bc5602.send_command(CMD_LIGHT_SLEEP)\n')
    ast.parse(check)
    check_output = output.with_name("rx_start_check.py")
    check_output.write_text(check)
    print(check_output)


if __name__ == "__main__":
    build()
